version: '3.8'

services:

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
    build: ./build/wp
    volumes:
      - ./wp:/var/www/html
      - ./config/apache2/sites-available:/etc/apache2/sites-available
      - ./config/php:/usr/local/etc/php

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080

  mysql:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - ./db:/var/lib/mysql